#!/usr/bin/env bash
# setup.sh - Full bootstrap for Odoo 19 docker-compose environment on Ubuntu/Debian
#
# What this script does:
# - Installs prerequisites (Docker Engine & Docker Compose plugin) on Ubuntu/Debian
# - Creates project directories
# - Generates a secure .env (if missing)
# - Creates a config/odoo.conf from the environment (if missing)
# - Optionally builds and starts the docker-compose stack
#
# Usage:
#   ./setup.sh [install|build|up|down|restart|ps|logs|status]
#   Default (no args) = install + build + up
#
# Notes:
# - Run on Ubuntu 20.04/22.04/24.04 or Debian-like systems.
# - The script attempts to be idempotent and safe for repeated runs.
# - After adding your user to the docker group you may need to re-login for the change to take effect.
set -euo pipefail

# ---------------------------------------------------------
# Configuration (edit only if you know what you're doing)
# ---------------------------------------------------------
PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_DIR="$PROJECT_DIR/config"
ADDONS_DIR="$PROJECT_DIR/addons"
DATA_DIR="$PROJECT_DIR/data"
PGDATA_DIR="$PROJECT_DIR/pgdata"
LOGS_DIR="$PROJECT_DIR/logs"
ENV_FILE="$PROJECT_DIR/.env"
DOCKER_COMPOSE_CMD=""   # autodetected later
ODOO_CONF="$CONFIG_DIR/odoo.conf"

# ---------------------------------------------------------
# Helpers
# ---------------------------------------------------------
echoinfo() { printf "\033[1;34m[INFO]\033[0m %s\n" "$*"; }
echowarn() { printf "\033[1;33m[WARN]\033[0m %s\n" "$*"; }
echoerr()  { printf "\033[1;31m[ERROR]\033[0m %s\n" "$*" >&2; }

command_exists() { command -v "$1" >/dev/null 2>&1; }

require_root() {
  if [ "$(id -u)" -ne 0 ]; then
    echoerr "This script needs to be run as root or with sudo for system installation steps."
    echoerr "Rerun with: sudo $0 $*"
    exit 1
  fi
}

# Create directories with correct ownership/perms
create_dirs() {
  echoinfo "Creating project directories..."
  mkdir -p "$CONFIG_DIR" "$ADDONS_DIR" "$DATA_DIR" "$PGDATA_DIR" "$LOGS_DIR"
  # Ensure user owns project files (if script run as non-root for file ops)
  if [ "$(id -u)" -ne 0 ]; then
    chown -R "$(id -u):$(id -g)" "$PROJECT_DIR"
  fi
  echoinfo "Directories: $CONFIG_DIR, $ADDONS_DIR, $DATA_DIR, $PGDATA_DIR, $LOGS_DIR"
}

# Generate a secure random hex string
randhex() {
  local len="${1:-32}"
  openssl rand -hex $(( (len+1)/2 )) 2>/dev/null | cut -c1-"$len"
}

# Create .env if missing
create_env_if_missing() {
  if [ -f "$ENV_FILE" ]; then
    echoinfo ".env already exists, skipping generation"
    return
  fi

  echoinfo "Creating secure .env file at $ENV_FILE"
  cat >"$ENV_FILE" <<EOF
# Auto-generated by setup.sh - review before production use
POSTGRES_DB=postgres
POSTGRES_USER=odoo
POSTGRES_PASSWORD=$(randhex 24)
# Odoo admin master password (Used to manage DBs)
ODOO_ADMIN_PASS=$(randhex 24)
# Odoo extra addons folder (host path)
EXTRA_ADDONS=/srv/extra-addons
EOF
  chmod 600 "$ENV_FILE"
  echoinfo "Created .env (permissions 600). Edit this file to change credentials."
}

# Create odoo.conf from environment if missing
create_odoo_conf_if_missing() {
  if [ -f "$ODOO_CONF" ]; then
    echoinfo "$ODOO_CONF already exists, skipping"
    return
  fi

  # Load values from .env (safe because we control its format)
  # shellcheck disable=SC1090
  # shellcheck disable=SC1091
  source "$ENV_FILE"

  echoinfo "Creating $ODOO_CONF from .env values"
  cat >"$ODOO_CONF" <<EOF
[options]
; Generated by setup.sh - review for production use
admin_passwd = ${ODOO_ADMIN_PASS}
db_host = db
db_port = 5432
db_user = ${POSTGRES_USER}
db_password = ${POSTGRES_PASSWORD}

addons_path = /opt/odoo/addons,/srv/extra-addons
data_dir = /var/lib/odoo

logfile = /var/log/odoo/odoo.log
log_level = info

xmlrpc = True
xmlrpc_port = 8069

# longpolling (chat)
longpolling_port = 8072

# Development-friendly defaults: workers = 0
workers = 0

proxy_mode = True

# Production limits (tune if you enable workers)
limit_time_cpu = 60
limit_time_real = 120
limit_memory_hard = 2684354560
EOF

  chmod 640 "$ODOO_CONF"
  echoinfo "Created $ODOO_CONF (permissions 640)"
}

# Detect docker compose command
detect_docker_compose_cmd() {
  if command_exists docker && docker compose version >/dev/null 2>&1; then
    DOCKER_COMPOSE_CMD="docker compose"
  elif command_exists docker-compose; then
    DOCKER_COMPOSE_CMD="docker-compose"
  else
    DOCKER_COMPOSE_CMD=""
  fi
}

# Install Docker Engine + compose plugin on Debian/Ubuntu
install_docker() {
  require_root

  if command_exists docker; then
    echoinfo "Docker already installed, skipping installation"
  else
    echoinfo "Installing Docker Engine (official repository)..."
    apt-get update
    apt-get install -y ca-certificates curl gnupg lsb-release software-properties-common

    # Add Docker's official GPG key
    mkdir -p /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    chmod a+r /etc/apt/keyrings/docker.gpg

    # Setup repository
    echo \
      "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
      $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null

    apt-get update
    apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

    systemctl enable --now docker
    echoinfo "Docker installed and started"
  fi

  # Add current user to docker group (if running non-root)
  if [ "$(id -u)" -ne 0 ]; then
    echoinfo "Adding $(whoami) to docker group (you may need to relogin to apply)"
    usermod -aG docker "$(whoami)" || true
  fi

  # detect compose cmd now
  detect_docker_compose_cmd
  if [ -z "$DOCKER_COMPOSE_CMD" ]; then
    echowarn "Docker Compose not found as plugin or standalone. You can use the 'docker compose' plugin or install docker-compose binary."
    echoinfo "Recommended: log out and back in (or run 'newgrp docker') then re-run this script."
  else
    echoinfo "Using compose command: $DOCKER_COMPOSE_CMD"
  fi
}

# Build images
do_build() {
  detect_docker_compose_cmd
  if [ -z "$DOCKER_COMPOSE_CMD" ]; then
    echoerr "Cannot find docker compose command. Try installing docker compose or use Docker Desktop."
    exit 1
  fi
  echoinfo "Building docker images (may take several minutes)..."
  (cd "$PROJECT_DIR" && $DOCKER_COMPOSE_CMD build --no-cache)
  echoinfo "Build finished."
}

# Start stack
do_up() {
  detect_docker_compose_cmd
  if [ -z "$DOCKER_COMPOSE_CMD" ]; then
    echoerr "Cannot find docker compose command. Try installing docker compose or use Docker Desktop."
    exit 1
  fi
  echoinfo "Starting services with docker compose..."
  (cd "$PROJECT_DIR" && $DOCKER_COMPOSE_CMD up -d)
  echoinfo "Stack started. Give the containers a few seconds to initialize."
  echoinfo "Check logs with: ./setup.sh logs"
}

do_down() {
  detect_docker_compose_cmd
  if [ -z "$DOCKER_COMPOSE_CMD" ]; then
    echoerr "Cannot find docker compose command."
    exit 1
  fi
  echoinfo "Stopping and removing containers..."
  (cd "$PROJECT_DIR" && $DOCKER_COMPOSE_CMD down)
}

do_ps() {
  detect_docker_compose_cmd
  if [ -z "$DOCKER_COMPOSE_CMD" ]; then
    echoerr "Cannot find docker compose command."
    exit 1
  fi
  (cd "$PROJECT_DIR" && $DOCKER_COMPOSE_CMD ps)
}

do_logs() {
  detect_docker_compose_cmd
  if [ -z "$DOCKER_COMPOSE_CMD" ]; then
    echoerr "Cannot find docker compose command."
    exit 1
  fi
  (cd "$PROJECT_DIR" && $DOCKER_COMPOSE_CMD logs -f --tail=200)
}

do_status() {
  echoinfo "System info:"
  uname -a
  echo
  echoinfo "Docker version:"
  docker --version || true
  echoinfo "Docker compose:"
  if docker compose version >/dev/null 2>&1; then
    docker compose version
  elif docker-compose version >/dev/null 2>&1; then
    docker-compose version
  else
    echowarn "Docker Compose not installed"
  fi
  echo
  echoinfo "Project directories and files:"
  ls -ld "$CONFIG_DIR" "$ADDONS_DIR" "$DATA_DIR" "$PGDATA_DIR" 2>/dev/null || true
  [ -f "$ENV_FILE" ] && echoinfo ".env exists at $ENV_FILE" || echowarn ".env missing"
  [ -f "$ODOO_CONF" ] && echoinfo "odoo.conf exists at $ODOO_CONF" || echowarn "odoo.conf missing"
}

# ---------------------------------------------------------
# Main
# ---------------------------------------------------------
ACTION="${1:-default}"

case "$ACTION" in
  install)
    echoinfo "Running install: install Docker & create files"
    install_docker
    create_dirs
    create_env_if_missing
    create_odoo_conf_if_missing
    echoinfo "Install step completed. You may need to log out/in for docker group changes."
    ;;

  build)
    create_dirs
    create_env_if_missing
    create_odoo_conf_if_missing
    do_build
    ;;

  up)
    create_dirs
    create_env_if_missing
    create_odoo_conf_if_missing
    do_up
    ;;

  down)
    do_down
    ;;

  restart)
    do_down
    do_up
    ;;

  ps)
    do_ps
    ;;

  logs)
    do_logs
    ;;

  status)
    do_status
    ;;

  default)
    # default = full setup + start
    echoinfo "Default action: install (if missing), build, up"
    install_docker
    create_dirs
    create_env_if_missing
    create_odoo_conf_if_missing
    do_build
    do_up
    ;;

  help|--help|-h)
    cat <<EOF
Usage: $0 [install|build|up|down|restart|ps|logs|status|help]
  install   - install Docker engine & compose plugin and create config/.env
  build     - build docker images (docker compose build)
  up        - start docker-compose stack (detached)
  down      - stop & remove containers
  restart   - down then up
  ps        - show docker-compose ps
  logs      - tail logs for the stack
  status    - quick system & project status
  help      - show this help
Default (no args): install (if needed) + build + up
EOF
    ;;

  *)
    echoerr "Unknown command: $ACTION"
    echo "Run: $0 help"
    exit 2
    ;;
esac

exit 0